#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start

new="\\\trewrite ^/redirect_me https://GitHub.com/YosriGFX permanent;"
sudo sed -i "29i $new" /etc/nginx/sites-available/default

sudo service nginx restart
sudo service nginx reload
