#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
namef="holbertonschool"
if [ -e "$namef" ];
then
	echo "$namef file exist"
	if [ -s "$namef" ];
	then
		echo "$namef file is not empty"
	else
		echo "$namef file is empty"
	fi
	if [ -f "$namef" ];
	then
		echo "$namef is a regular file"
	fi
else
	echo "$namef file does not exists"
fi
