#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
a=$(file holbertonschool | cut -d ' ' -f2)
if [ "$a" == "cannot" ]
then
	echo "holbertonschool file does not exist"
else
	echo "holbertonschool file exists"
	if [ "$a" == "empty" ]
	then
		echo "holbertonschool is empty"
	else
		echo "holbertonschool file is not empty"
	fi
	if [ "$a" != "directory" ]
	then
		echo "holbertonschool is a regular file"
	fi
fi
